extends RefCounted

static var language := "en-US"
static var changed: Signal

const TEXT := {
	"en-US": {
		"Gambar": "Draw", "Gambar B": "Draw B", "Navigasi N": "Navigate N", "Pilih V": "Select V",
		"Hapus E": "Erase E", "Sembunyikan U": "Hide U", "Menu U": "Menu U", "Panduan ikon": "Icon guide",
		"Jari: putar": "Finger: orbit", "Jari: gambar": "Finger: draw", "Pilih warna brush": "Brush color",
		"Warna": "Color", "Radius": "Radius", "Pena": "Pen", "Pensil tekstur": "Textured pencil",
		"Draw Shape": "Draw Shape",
		"Kuas tekstur": "Textured brush", "Tube 3D (lama)": "3D tube (legacy)", "Lasso Fill": "Lasso Fill",
		"Rectangle Fill": "Rectangle Fill", "Opacity brush": "Brush opacity", "Ujung meruncing": "Tapered ends",
		"Loft": "Loft", "Pilih minimal dua stroke untuk Loft.": "Select at least two strokes for Loft.",
		"Loft tension": "Loft tension",
		"Haluskan goresan": "Smooth stroke", "PROYEK": "PROJECT", "Simpan": "Save", "Buka": "Open",
		"Simpan sebagai...": "Save as...", "GRUP AKTIF": "ACTIVE GROUP", "Hapus": "Delete",
		"Duplikat": "Duplicate", "Gabung": "Merge", "Ubah": "Rename", "Tampilkan grup": "Show group",
		"Pindah ke grup aktif": "Move to active group", "Hapus pilihan": "Delete selection",
		"Duplikat grup": "Duplicate group", "Hapus grup": "Delete group", "Belum ada seleksi": "No selection",
		"LIQUIFY": "LIQUIFY", "Mulai Liquify": "Start Liquify", "Undo All": "Undo All",
		"Compare": "Compare", "Apply": "Apply", "Ukuran": "Size", "Range": "Range", "Strength": "Strength",
		"Mirror": "Mirror", "Buat bidang: tarik area": "Create plane: drag an area",
		"SEQUENCE": "SEQUENCE", "Add Shot": "Add Shot", "Move Left": "Move Left", "Move Right": "Move Right",
		"Play": "Play", "Pause": "Pause", "Previous": "Previous", "Next": "Next", "Stop Playback": "Stop Playback", "Sembunyikan semua menu": "Hide all menus", "Tampilkan kembali semua menu (U)": "Show all menus (U)", "Open color, groups, sequence, and project tools": "Open color, groups, sequence, and project tools",
		"Once": "Once", "Loop": "Loop", "Swing": "Swing",
		"UI Always On": "UI Always On", "Thirds Grid": "Thirds Grid", "Camera Info": "Camera Info",
		"Export 360 GIF": "Export 360 GIF",
		"GIF export failed.": "GIF export failed.",
		"360 GIF exported.": "360 GIF exported.",
		"Select shot for ordering": "Select shot for ordering",
		"Bidang ukuran otomatis": "Auto-size plane", "Draw: profil bebas": "Draw: free profile",
		"Bend: gambar arah baru": "Bend: draw new direction", "Batal membuat guide": "Cancel guide creation",
		"Simpan guide": "Save guide", "Tutup": "Close", "Hadap guide": "Face guide",
		"Aktifkan guide": "Activate guide", "Tampil / sembunyi": "Show / hide",
		"Hapus guide tersimpan": "Delete saved guide", "Reset kamera": "Reset camera", "Tampak": "View",
		"3D GUIDE": "3D GUIDE", "GUIDE TERSIMPAN": "SAVED GUIDES", "English (US)": "English (US)",
		"Bahasa Indonesia": "Indonesian", "Bahasa / Language": "Language", "Perspective": "Perspective", "Orthographic": "Orthographic",
		"1 jari: putar / gambar   •   2 jari: pan / zoom   •   ? Panduan ikon": "1 finger: orbit / draw   •   2 fingers: pan / zoom   •   ? Icon guide",
		"Panduan ikon • WolfDraw3D": "Icon Guide • WolfDraw3D",
		"Arahkan mouse ke ikon untuk tooltip. Di layar sentuh, buka panduan ini lewat ikon tanda tanya.\nHijau = aktif • Redup = belum tersedia.\n\nSatu jari: putar atau gambar sesuai ikon tangan.\nDua jari: geser untuk pan, cubit/renggangkan untuk zoom.\nDraw Shape: tahan ujung sekitar 1 detik, atur bentuk, lalu lepaskan.": "Hover over an icon for its tooltip. On touch screens, open this guide with the question-mark icon.\nGreen = active • Dim = unavailable.\n\nOne finger: orbit or draw according to the hand icon.\nTwo fingers: drag to pan, pinch/spread to zoom.\nDraw Shape: hold an endpoint for about one second, adjust the shape, then release.",
		"Geser X+": "Move X+",
		"Geser X-": "Move X-",
		"Geser Y+": "Move Y+",
		"Geser Y-": "Move Y-",
		"Geser Z+": "Move Z+",
		"Geser Z-": "Move Z-",
		"Memindahkan grup 0,25 unit pada sumbu X+.": "Move the group 0.25 units along axis X+.",
		"Memindahkan grup 0,25 unit pada sumbu X-.": "Move the group 0.25 units along axis X-.",
		"Memindahkan grup 0,25 unit pada sumbu Y+.": "Move the group 0.25 units along axis Y+.",
		"Memindahkan grup 0,25 unit pada sumbu Y-.": "Move the group 0.25 units along axis Y-.",
		"Memindahkan grup 0,25 unit pada sumbu Z+.": "Move the group 0.25 units along axis Z+.",
		"Memindahkan grup 0,25 unit pada sumbu Z-.": "Move the group 0.25 units along axis Z-.",
		"Perspektif": "Perspective", "Ortografis": "Orthographic", "Belum ada guide aktif": "No active guide",
		"Bentangan profil: 4.0": "Profile sweep: 4.0", "Kedalaman guide baru": "New guide depth",
		"Draw Shape: mati": "Draw Shape: off", "Draw Shape: otomatis": "Draw Shape: automatic",
		"Bidang: tarik area": "Plane: drag area",
		"Tap: tambah/hapus": "Tap: add/remove",
		"Rectangle": "Rectangle",
		"Lasso": "Lasso",
		"Radius eraser": "Eraser radius",
		"Seleksi tap: ketuk untuk tambah/hapus": "Tap selection: tap to add/remove",
		"Seleksi rectangle": "Rectangle selection",
		"Seleksi lasso": "Lasso selection",
		"Buat bidang guide atau aktifkan guide tersimpan sebelum menggambar.": "Create a guide plane or activate a saved guide before drawing.",
		"Batas ukuran proyek tercapai. Hapus goresan sebelum melanjutkan.": "Project size limit reached. Delete strokes before continuing.",
		"Grup aktif tersembunyi. Aktifkan Tampilkan grup sebelum menggambar.": "The active group is hidden. Enable Show group before drawing.",
		"Gambar di dalam guide aktif; gunakan Hadap guide jika terlihat dari samping.": "Draw inside the active guide; use Face guide if it is viewed from the side.",
		"Batas 200.000 titik tercapai.": "The 200,000-point limit has been reached.",
		"Isi area harus berada di dalam guide aktif.": "The fill area must be inside the active guide.",
		"Area isi harus seluruhnya berada di dalam guide.": "The fill area must be entirely inside the guide.",
		"Area terisi dengan warna aktif.": "Area filled with the active color.",
		"Batas ukuran proyek tercapai. Mirror dilewati.": "Project size limit reached. Mirror skipped.",
		"Pilih minimal satu goresan sebelum Liquify.": "Select at least one stroke before Liquify.",
		"Perubahan Liquify dibatalkan.": "Liquify changes canceled.",
		"Liquify diterapkan.": "Liquify applied.",
		"Liquify active: %s. Drag on strokes, then Apply.": "Liquify active: %s. Drag on strokes, then Apply.",
		"Compare: before Liquify.": "Compare: before Liquify.",
		"Compare: Liquify result.": "Compare: Liquify result.",
		"Mirror active: ": "Mirror active: ",
		"Mirror inactive": "Mirror inactive",
		"Batas 1.000 grup tercapai.": "The 1,000-group limit has been reached.",
		"Batas ukuran proyek tercapai.": "The project size limit has been reached.",
		"%d strokes in group '%s' selected.": "%d strokes in group '%s' selected.",
		"%d duplicates created and selected.": "%d duplicates created and selected.",
		"Minimal satu grup harus dipertahankan.": "At least one group must be kept.",
		"Pilih minimal dua grup untuk digabung.": "Select at least two groups to merge.",
		"Batas ukuran proyek tercapai. Hapus goresan sebelum menduplikasi.": "Project size limit reached. Delete strokes before duplicating.",
		"Autosave gagal": "Autosave failed",
		"Autosave failed: ": "Autosave failed: ",
		"Gunakan Simpan.": "Use Save.",
		"Draw Shape: tahan aktif — geser untuk mengatur bentuk, lepas untuk selesai.": "Draw Shape: hold is active — drag to adjust the shape, release to finish.",
		"Koreksi keluar batas guide; bentuk sebelumnya dipertahankan.": "Correction exceeded the guide bounds; the previous shape was kept.",
		"Bentuk terlalu kecil; goresan sebelumnya dipertahankan.": "The shape is too small; the previous stroke was kept.",
		"Potongan eraser melebihi batas proyek.": "The eraser cut exceeded the project limit.",
		"Tutup atau simpan guide aktif sebelum membuat guide baru.": "Close or save the active guide before creating a new guide.",
		"Batas 100 guide tercapai.": "The limit of 100 guides has been reached.",
		"Batas 200.000 vertex guide tercapai.": "The 200,000 guide-vertex limit has been reached.",
		"Ukuran brush tidak valid.": "Invalid brush size.",
		"Warna goresan tidak valid.": "Invalid stroke color.",
		"Ukuran mesh guide tidak valid.": "Invalid guide mesh size.",
		"Ukuran proyek melebihi 32 MB.": "Project size exceeds 32 MB.",
		"Pulihkan sesi sebelumnya?": "Restore previous session?",
		"Ada autosave dari sesi sebelumnya.\nPulihkan untuk melanjutkan gambar yang belum disimpan.": "An autosave from a previous session is available.\nRestore it to continue the unsaved drawing.",
		"Pulihkan": "Restore",
		"Mulai kosong": "Start fresh",
		"Buka proyek lain?": "Open another project?",
		"Perubahan belum disimpan ke file proyek.\nSimpan terlebih dahulu jika ingin mempertahankannya.": "Changes have not been saved to the project file.\nSave first if you want to keep them.",
		"Buka tanpa menyimpan": "Open without saving",
		"Gagal menyimpan. Proyek tetap terbuka.": "Save failed. The project remains open.",
		"Proyek yang sedang dibuka tidak diubah.": "The open project was not changed.",
		"File utama tidak terbaca. Proyek dipulihkan dari cadangan .bak; simpan sebagai file baru.": "The main file could not be read. The project was restored from the .bak backup; save it as a new file.",
		"Autosave gagal. Simpan proyek ke lokasi lain sebelum menutup aplikasi.": "Autosave failed. Save the project to another location before closing the application.",
		"Coba garis dengan arah atau bentangan berbeda.": "Try a line with a different direction or sweep.",
		"Bentuk: garis": "Shape: line", "Bentuk: lingkaran": "Shape: circle",
		"Bentuk: elips": "Shape: ellipse", "Bentuk: kurva": "Shape: curve",
		"Proyek baru": "New project", "Tanpa guide": "No guide",
		"Guide actif": "Active guide", "Membuat guide": "Creating guide", "1 jari: putar / gambar": "1 finger: orbit / draw",
		"2 jari: pan / zoom": "2 fingers: pan / zoom",
		"Opacity guide": "Guide opacity", "Tutup panduan": "Close guide", "goresan": "strokes",
		"Navigasi": "Navigate", "Seleksi": "Select",
		"Gambar garis Bend": "Draw Bend line", "Gambar profil bebas": "Draw free profile",
		"Tarik area di kanvas": "Drag an area on the canvas", "aktif": "active",
		"Bentangan profil": "Profile sweep",
		"Menggambar pada guide aktif. Pintasan B.": "Draw on the active guide. Shortcut B.",
		"Memutar kamera. Satu jari orbit; dua jari pan/cubit zoom. Pintasan N.": "Orbit the camera. One finger orbits; two fingers pan/pinch to zoom. Shortcut N.",
		"Memilih satu goresan untuk diedit. Pintasan V.": "Select a stroke to edit. Shortcut V.",
		"Menghapus bagian goresan dalam sapuan eraser. Pintasan E.": "Erase part of a stroke. Shortcut E.",
		"Membatalkan satu perubahan. Ctrl+Z.": "Undo one change. Ctrl+Z.",
		"Mengulangi perubahan yang dibatalkan. Ctrl+Shift+Z.": "Redo an undone change. Ctrl+Shift+Z.",
		"Menyembunyikan panel untuk memperluas kanvas. Pintasan U.": "Hide panels to expand the canvas. Shortcut U.",
		"Menampilkan kembali panel. Pintasan U.": "Show the panels again. Shortcut U.",
		"Langsung membuat guide datar di depan kamera.": "Create a flat guide in front of the camera.",
		"Menarik area untuk membuat guide datar. Pintasan G.": "Drag an area to create a flat guide. Shortcut G.",
		"Membuka pilihan tampak depan, belakang, atas, bawah, kanan, dan kiri.": "Open front, back, top, bottom, right, and left views.",
		"Memindahkan goresan terpilih ke grup aktif.": "Move selected strokes to the active group.",
		"Menampilkan atau menyembunyikan joystick transformasi grup.": "Show or hide the group transform gizmo.",
		"Sapu untuk menghapus sebagian goresan. Goresan bertumpuk di area layar yang sama ikut terpotong; grup tersembunyi dilindungi.": "Brush to erase part of a stroke. Overlapping strokes in the same screen area are also cut; hidden groups are protected.",
		"Putar: satu jari untuk orbit. Gambar: satu jari memakai alat aktif. Dua jari selalu pan dan cubit untuk zoom.": "Orbit: one finger orbits. Draw: one finger uses the active tool. Two fingers always pan and pinch to zoom.",
		"Klik untuk memilih warna atau memasukkan kode HEX.": "Click to choose a color or enter a HEX code.",
		"Klik: grup aktif. Tekan-tahan belum diperlukan; gunakan Ctrl di PC atau tombol Multi.": "Click: make this the active group. Use the multi-select button for multiple groups.",
		"Pilih atau lepas grup untuk operasi multi-grup.": "Select or deselect this group for multi-group operations.",
		"Menampilkan atau menyembunyikan grup aktif. Hijau berarti tampil.": "Show or hide the active group. Green means visible.",
		"Menyalin goresan terpilih sebagai goresan baru.": "Copy selected strokes as new strokes.",
		"Menghapus seluruh goresan terpilih. Delete/Backspace.": "Delete all selected strokes. Delete/Backspace.",
		"Membuat grup baru.": "Create a new group.",
		"Menerapkan nama grup dari kolom di sebelah ikon.": "Apply the group name from the field beside the icon.",
		"Menampilkan kembali semua menu (U)": "Show all menus again (U)",
		"Satu jari memutar kamera. Ketuk untuk beralih ke jari menggambar.": "One finger orbits the camera. Tap to switch to drawing finger mode.",
		"Satu jari memakai alat aktif. Ketuk untuk kembali memutar. Dua jari selalu navigasi.": "One finger uses the active tool. Tap to return to orbit mode. Two fingers always navigate.",
		"Menyimpan proyek ke file. Ctrl+S.": "Save the project to a file. Ctrl+S.",
		"Membuka file proyek. Ctrl+O.": "Open a project file. Ctrl+O.",
		"Menyimpan proyek ke file baru. Ctrl+Shift+S.": "Save the project to a new file. Ctrl+Shift+S.",
		"Membuat guide dari profil bebas yang ditarik pada kanvas.": "Create a guide from a free profile drawn on the canvas.",
		"Mengubah bentangan guide dengan garis baru, dimulai dari sisi oranye.": "Change the guide sweep with a new line, starting from the orange edge.",
		"Membatalkan pembuatan atau Bend guide.": "Cancel guide creation or Bend.",
		"Simpan guide sebagai resource dan melepas target gambar. Simpan proyek untuk menulis ke disk.": "Save the guide as a resource and release the drawing target. Save the project to write it to disk.",
		"Menutup guide aktif tanpa menghapus tinta. Pintasan Esc.": "Close the active guide without deleting ink. Shortcut Esc.",
		"Mengarahkan kamera ke guide aktif.": "Aim the camera at the active guide.",
		"Memakai guide tersimpan yang dipilih sebagai target gambar.": "Use the selected saved guide as the drawing target.",
		"Mengubah visibilitas guide tersimpan yang dipilih.": "Toggle visibility of the selected saved guide.",
		"Menghapus guide tersimpan, tinta tetap ada.": "Delete the saved guide; ink remains.",
		"Mengembalikan posisi, pusat, dan jarak kamera ke awal.": "Reset the camera position, target, and distance.",
		"Mengaktifkan taper untuk sapuan baru. Hijau berarti aktif.": "Enable taper for new strokes. Green means enabled.",
		"Menghaluskan goresan pada guide datar. Hijau berarti aktif.": "Smooth strokes on a flat guide. Green means enabled.",
		"Memutar grup -15 derajat terhadap normal guide.": "Rotate the active group -15 degrees around the guide normal.",
		"Memutar grup +15 derajat terhadap normal guide.": "Rotate the active group +15 degrees around the guide normal.",
		"Memperkecil grup aktif.": "Scale down the active group.",
		"Memperbesar grup aktif.": "Scale up the active group.",
		"Mencerminkan sapuan baru pada sumbu X, Y, atau Z.": "Mirror new strokes on the X, Y, or Z axis.",
		"Geser grup aktif 0,25 unit pada sumbu X+": "Move the active group 0.25 units along axis X+.",
		"Geser grup aktif 0,25 unit pada sumbu X-": "Move the active group 0.25 units along axis X-.",
		"Geser grup aktif 0,25 unit pada sumbu Y+": "Move the active group 0.25 units along axis Y+.",
		"Geser grup aktif 0,25 unit pada sumbu Y-": "Move the active group 0.25 units along axis Y-.",
		"Geser grup aktif 0,25 unit pada sumbu Z+": "Move the active group 0.25 units along axis Z+.",
		"Geser grup aktif 0,25 unit pada sumbu Z-": "Move the active group 0.25 units along axis Z-.",
		"Gambar bebas, tahan ujung sekitar 1 detik untuk merapikan, lalu geser tanpa melepas. Lepas sebelum ditahan untuk tetap bebas.": "Draw freely; hold an endpoint for about one second to refine, then drag without releasing. Release before holding to stay free.",
		"Gambar satu garis bebas sebagai tepi awal guide, lalu orbit untuk melihat permukaannya.": "Draw a free line as the guide edge, then orbit to view its surface.",
		"Garis baru mengganti arah bentangan dari tepi oranye. Tinta yang sudah ada tetap di tempat.": "The new line changes the sweep direction from the orange edge. Existing ink stays in place.",
		"Simpan sebagai resource dan nonaktifkan. Goresan tetap ada. Gunakan Simpan proyek untuk menulis ke disk.": "Save as a resource and deactivate. Strokes remain. Use Save project to write to disk."
	},
	"id": {
		"Draw": "Gambar", "Draw B": "Gambar B", "Navigate N": "Navigasi N", "Select V": "Pilih V",
		"Erase E": "Hapus E", "Hide U": "Sembunyikan U", "Menu U": "Menu U", "Icon guide": "Panduan ikon",
		"Finger: orbit": "Jari: putar", "Finger: draw": "Jari: gambar", "Brush color": "Pilih warna brush",
		"Pen": "Pena", "Textured pencil": "Pensil tekstur", "Textured brush": "Kuas tekstur",
		"Draw Shape": "Bentuk gambar",
		"3D tube (legacy)": "Tube 3D (lama)", "Brush opacity": "Opacity brush", "Tapered ends": "Ujung meruncing",
		"Loft": "Loft", "Pilih minimal dua stroke untuk Loft.": "Pilih minimal dua stroke untuk Loft.",
		"Loft tension": "Tegangan Loft",
		"Smooth stroke": "Haluskan goresan", "PROJECT": "PROYEK", "Save": "Simpan", "Open": "Buka",
		"Save as...": "Simpan sebagai...", "ACTIVE GROUP": "GRUP AKTIF", "Delete": "Hapus",
		"Duplicate": "Duplikat", "Merge": "Gabung", "Rename": "Ubah", "Show group": "Tampilkan grup",
		"Move to active group": "Pindah ke grup aktif", "Delete selection": "Hapus pilihan",
		"Duplicate group": "Duplikat grup", "Delete group": "Hapus grup", "No selection": "Belum ada seleksi", "Stop Playback": "Hentikan playback", "Sembunyikan semua menu": "Sembunyikan semua menu", "Tampilkan kembali semua menu (U)": "Tampilkan semua menu (U)", "Open color, groups, sequence, and project tools": "Buka warna, grup, sequence, dan tool proyek",
		"Start Liquify": "Mulai Liquify", "SEQUENCE": "SEQUENCE", "Add Shot": "Tambah Shot", "Move Left": "Geser kiri", "Move Right": "Geser kanan", "Play": "Putar", "Pause": "Jeda", "Previous": "Sebelumnya", "Next": "Berikutnya", "Once": "Sekali", "Loop": "Ulangi", "Swing": "Bolak-balik", "Language": "Bahasa / Language", "English (US)": "English (US)",
		"Indonesian": "Bahasa Indonesia", "Perspective": "Perspektif", "Orthographic": "Ortografis", "Create plane: drag an area": "Buat bidang: tarik area",
		"Auto-size plane": "Bidang ukuran otomatis", "Draw: free profile": "Draw: profil bebas",
		"Bend: draw new direction": "Bend: gambar arah baru", "Cancel guide creation": "Batal membuat guide",
		"Save guide": "Simpan guide", "Close": "Tutup", "Face guide": "Hadap guide",
		"Activate guide": "Aktifkan guide", "Show / hide": "Tampil / sembunyi", "Delete saved guide": "Hapus guide tersimpan",
		"Reset camera": "Reset kamera", "View": "Tampak", "SAVED GUIDES": "GUIDE TERSIMPAN"
	}
}

static func translate(text: String) -> String:
	var table: Dictionary = TEXT.get(language, TEXT["en-US"])
	return str(table.get(text, text))

static func set_language(value: String) -> void:
	language = value
